# Minecraft Plugin YML
name: HaloMobs
main: me.gomq.halomobs.HaloMobs
version: 0.1.0
api-version: 1.18
author: GomQ
description: Minecraft Plugin for Halloween Server
website: https://github.com/igomq/HaloMobs